WebApplication2/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace WebApplication2.Controllers
{
    public class ReservasController : Controller
    {
        private conDB conn = new conDB();
        // GET: Reservas
        public ActionResult Index()
        {
            return View(conn.tb_reserva.ToList());
        }
        public ActionResult New()
        {
            ViewBag.ListaCliente = conn.tb_cliente.ToList();
            ViewBag.ListaMascota = conn.tb_mascota.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult New(tb_reserva res)
        {
            conn.tb_reserva.Add(res);
            conn.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(string id)
        {
            tb_reserva res = new tb_reserva();
            res = conn.tb_reserva.Find(id);
            return View(res);
        }
        [HttpPost]
        public ActionResult Edit(tb_reserva resnew)
        {
            tb_reserva res = new tb_reserva();
            res = conn.tb_reserva.Find(resnew.id_res);
            res.fec_res = resnew.fec_res;
            res.id_cli = resnew.id_cli;
            res.id_mas = resnew.id_mas;
            conn.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(string id)
        {
            conn.tb_reserva.Remove(conn.tb_reserva.Find(id));

            conn.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication2/Views/Reservas/Edit.cshtml
@using DAO
@model  tb_reserva
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.id_mas)
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.id_res, new { @class = "control-label" })
        @*<label>@Model.id_cli</label>*@
        @Html.TextBoxFor(model => model.id_res, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.fec_res, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.fec_res, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
            @Html.LabelFor(modelo => modelo.id_cli, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.id_cli, htmlAttributes: new { @class = "form-control", @readonly="readonly"  })
        </div>
        <div class="form-group">
            @Html.LabelFor(modelo => modelo.id_mas, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.id_mas, htmlAttributes: new { @class = "form-control", @readonly="readonly"  })
        </div>
    <div class="form-group">
        <input type="submit" value="Registrar" class="btn btn-success" />
    </div>
</div>
}

WebApplication2/Views/Reservas/Index.cshtml
@using DAO
@model List<tb_reserva>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Reservas</h2>
@*<a onclick="modalCrearCategoria()" class="btn btn-info glyphicon glyphicon-plus" title="Nuevo Cliente"></a>*@
@Html.ActionLink("Crear", "New", "Reservas")
<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Fecha Reserva</td>
            <td>Id Cliente</td>
            <td>Nombre Cliente</td>
            <td>Apellidos Cliente</td>
            <td>Id Mascota</td>
            <td>Nombre Mascota</td>
            <td>Acción</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.id_res</td>
            <td>@item.fec_res</td>
            <td>@item.id_cli</td>
            <td>@item.tb_cliente.nom_cli</td>
            <td>@item.tb_cliente.ape_cli</td>
            <td>@item.id_mas</td>
            <td>@item.tb_mascota.nom_mas</td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id_res }) |
                @Html.ActionLink(" ", "Delete", new { id = item.id_res }, new
           {
               @class = "btn btn-danger glyphicon glyphicon-remove",
               @title = "Eliminar",
               @onclick = "return confirm('¿Desea eliminar la Categoría?');"
           })
            </td>
        </tr>
        }
    </tbody>
</table>

WebApplication2/Views/Reservas/New.cshtml
@using DAO;
@model tb_reserva
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar Nueva Reserva</h2>
@using (Html.BeginForm())
{
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.id_res, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.id_res, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.fec_res, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.fec_res, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.id_cli, new { @class = "control-label" })
        <select class="form-control" name="id_cli">
            @foreach (var item in ViewBag.ListaCliente)
            {
                <option value="@item.id_cli">@item.id_cli</option>
            }
        </select>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.id_mas, new { @class = "control-label" })
        <select class="form-control" name="id_mas">
            @foreach (var item in ViewBag.ListaMascota)
            {
                <option value="@item.id_mas">@item.id_mas</option>
            }
        </select>
    </div>
    <div class="form-group">
        <input type="submit" value="Registrar" class="btn btn-success" />
    </div>
</div>
}