WebApplication2/Controllers/MascotasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace WebApplication2.Controllers
{
    public class MascotasController : Controller
    {
        private conDB conn = new conDB();
        // GET: Mascotas
        public ActionResult Index()
        {
            return View(conn.tb_mascota.ToList());
        }
        public ActionResult New()
        {
            ViewBag.ListaCliente = conn.tb_cliente.ToList();
            ViewBag.ListaTipoMascota= conn.tb_tipoMascota.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult New(tb_mascota mas)
        {
            conn.tb_mascota.Add(mas);
            conn.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(string id)
        {
            tb_mascota mas = new tb_mascota();
            mas = conn.tb_mascota.Find(id);
            return View(mas);
        }
        [HttpPost]
        public ActionResult Edit(tb_mascota masnew)
        {
            tb_mascota mas = new tb_mascota();
            mas = conn.tb_mascota.Find(masnew.id_mas);
            mas.nom_mas = masnew.nom_mas;
            mas.fecNacimiento_mas = masnew.fecNacimiento_mas;
            mas.raza_mas = masnew.raza_mas;
            mas.id_cli = masnew.id_cli;
            mas.id_tipMas = masnew.id_tipMas;
            conn.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(string id)
        {
            conn.tb_mascota.Remove(conn.tb_mascota.Find(id));

            conn.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication2/Views/Mascotas/Edit.cshtml
@using DAO
@model  tb_mascota
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.id_mas)
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.id_mas, new { @class = "control-label" })
        @*<label>@Model.id_cli</label>*@
        @Html.TextBoxFor(model => model.id_mas, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.nom_mas, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.nom_mas, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.fecNacimiento_mas, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.fecNacimiento_mas, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.raza_mas, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.raza_mas, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
            @Html.LabelFor(modelo => modelo.id_cli, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.id_cli, htmlAttributes: new { @class = "form-control", @readonly="readonly"  })
        </div>
        <div class="form-group">
            @Html.LabelFor(modelo => modelo.id_tipMas, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.id_tipMas, htmlAttributes: new { @class = "form-control", @readonly="readonly"  })
        </div>
    <div class="form-group">
        <input type="submit" value="Registrar" class="btn btn-success" />
    </div>
</div>
}
    

WebApplication2/Views/Mascotas/Index.cshtml
@using DAO
@model List<tb_mascota>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Mascota</h2>
@*<a onclick="modalCrearCategoria()" class="btn btn-info glyphicon glyphicon-plus" title="Nuevo Cliente"></a>*@
@Html.ActionLink("Crear", "New", "Mascotas")
<table class="table">
    <thead>
        <tr>
            <td>Identificador</td>
            <td>Nombre</td>
            <td>Fecha Nacimiento</td>
            <td>Raza</td>
            <td>Id Cliente</td>
            <td>Id Tipo Mascota</td>
            <td>Descripción Tipo Mascota</td>
            <td>Acción</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.id_mas</td>
            <td>@item.nom_mas</td>
            <td>@item.fecNacimiento_mas</td>
            <td>@item.raza_mas</td>
            <td>@item.id_cli</td>
            <td>@item.id_tipMas</td>
            <td>@item.tb_tipoMascota.descripcion_tipMas</td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id_mas }) |
                @Html.ActionLink(" ", "Delete", new { id = item.id_mas }, new
           {
               @class = "btn btn-danger glyphicon glyphicon-remove",
               @title = "Eliminar",
               @onclick = "return confirm('¿Desea eliminar la Categoría?');"
           })
            </td>
        </tr>
        }
    </tbody>
</table>

WebApplication2/Views/Mascotas/New.cshtml
@using DAO;
@model tb_mascota
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Regsitrar Nueva Mascota</h2>
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.id_mas, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.id_mas, htmlAttributes: new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.nom_mas, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.nom_mas, htmlAttributes: new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.fecNacimiento_mas, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.fecNacimiento_mas, htmlAttributes: new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.raza_mas, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.raza_mas, htmlAttributes: new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.id_cli, new { @class = "control-label" })
            <select class="form-control" name="id_cli">
                @foreach (var item in ViewBag.ListaCliente)
                {
                    <option value="@item.id_cli">@item.id_cli</option>
                }
            </select>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.id_tipMas, new { @class = "control-label" })
            <select class="form-control" name="id_tipMas">
                @foreach (var item in ViewBag.ListaTipoMascota)
                {
                    <option value="@item.id_tipMas">@item.descripcion_tipMas</option>
                }
            </select>
        </div>
        <div class="form-group">
            <input type="submit" value="Registrar" class="btn btn-success" />
        </div>
    </div>
}