WebApplication2/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace WebApplication2.Controllers
{
    public class ClientesController : Controller
    {
        private conDB conn = new conDB();
        // GET: Clientes
        public ActionResult Index()
        {
            return View(conn.tb_cliente.ToList());
        }
        [HttpGet]
        public ActionResult New()
        {
            return View();
        }
        [HttpPost]
        public ActionResult New(tb_cliente cli)
        {
            conn.tb_cliente.Add(cli);
            conn.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(string id)
        {
            tb_cliente cli = new tb_cliente();
            cli = conn.tb_cliente.Find(id);
            return View(cli);
        }
        [HttpPost]
        public ActionResult Edit(tb_cliente clinew)
        {
            tb_cliente cli = new tb_cliente();
            cli = conn.tb_cliente.Find(clinew.id_cli);
            cli.nom_cli = clinew.nom_cli;
            cli.ape_cli = clinew.ape_cli;
            cli.telFijo_cli = clinew.telFijo_cli;
            cli.telMovil_cli = clinew.telMovil_cli;
            cli.cor_cli = clinew.cor_cli;
            cli.dir_cli = clinew.dir_cli;
            conn.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(string id)
        {
            conn.tb_cliente.Remove(conn.tb_cliente.Find(id));

            conn.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication2/Views/Clientes/Edit.cshtml
@using DAO
@model  tb_cliente
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.id_cli)
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.id_cli, new { @class = "control-label" })
        @*<label>@Model.id_cli</label>*@
        @Html.TextBoxFor(model => model.id_cli, htmlAttributes: new { @class = "form-control", @readonly="readonly" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.nom_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.nom_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.ape_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.ape_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.telFijo_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.telFijo_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.telMovil_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.telMovil_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.cor_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.cor_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.dir_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.dir_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" value="Registrar" class="btn btn-success" />
    </div>
</div>
}

WebApplication2/Views/Clientes/Index.cshtml
@using DAO
@model List<tb_cliente>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Cliente</h2>
@*<a onclick="modalCrearCategoria()" class="btn btn-info glyphicon glyphicon-plus" title="Nuevo Cliente"></a>*@
@Html.ActionLink("Crear", "New", "Clientes")
<table class="table">
    <thead>
        <tr>
            <td>Identificador</td>
            <td>Nombre</td>
            <td>Apellidos</td>
            <td>Telefono Fijo</td>  
            <td>Celular</td>
            <td>Correo Electrónico</td>
            <td>Dirección</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.id_cli</td>
            <td>@item.nom_cli</td>
            <td>@item.ape_cli</td>
            <td>@item.telFijo_cli</td>
            <td>@item.telMovil_cli</td>
            <td>@item.cor_cli</td>
            <td>@item.dir_cli</td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id_cli }) |
                @Html.ActionLink(" ", "Delete", new { id = item.id_cli }, new
                {
                    @class = "btn btn-danger glyphicon glyphicon-remove",
                    @title = "Eliminar",
                    @onclick = "return confirm('¿Desea eliminar la Categoría?');"
                })
            </td>
        </tr>}
    </tbody>
</table>

WebApplication2/Views/Clientes/New.cshtml
@using DAO;
@model tb_cliente
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar Nuevo Cliente</h2>
@using (Html.BeginForm())
{
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.id_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.id_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.nom_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.nom_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ape_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.ape_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.telFijo_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.telFijo_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.telMovil_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.telMovil_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.cor_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.cor_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.dir_cli, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.dir_cli, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" value="Registrar" class="btn btn-success" />
    </div>
</div>
}