WebApplication2/Controllers/ConsultasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace WebApplication2.Controllers
{
    public class ConsultasController : Controller
    {
        private conDB conn = new conDB();
        // GET: Consultas
        public ActionResult Index()
        {
            return View(conn.tb_consulta.ToList());
        }
        [HttpGet]
        public ActionResult New()
        {
            ViewBag.ListaMascota = conn.tb_mascota.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult New(tb_consulta cons)
        {
            conn.tb_consulta.Add(cons);
            conn.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(string id)
        {
            tb_consulta cons = new tb_consulta();
            cons = conn.tb_consulta.Find(id);
            return View(cons);
        }
        [HttpPost]
        public ActionResult Edit(tb_consulta consnew)
        {
            tb_consulta cons = new tb_consulta();
            cons = conn.tb_consulta.Find(consnew.id_cons);
            cons.fec_cons = consnew.fec_cons;
            cons.sint_cons = consnew.sint_cons;
            cons.diag_cons = consnew.diag_cons;
            cons.id_mas = consnew.id_mas;
            conn.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(string id)
        {
            conn.tb_consulta.Remove(conn.tb_consulta.Find(id));

            conn.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication2/Views/Consultas/Edit.cshtml
@using DAO
@model  tb_consulta
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.id_cons)
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.id_cons, new { @class = "control-label" })
        @*<label>@Model.id_cli</label>*@
        @Html.TextBoxFor(model => model.id_cons, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.fec_cons, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.fec_cons, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.sint_cons, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.sint_cons, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(modelo => modelo.diag_cons, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.diag_cons, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
            @Html.LabelFor(modelo => modelo.id_mas, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.id_mas, htmlAttributes: new { @class = "form-control" , @readonly="readonly" })
        </div>
    <div class="form-group">
        <input type="submit" value="Registrar" class="btn btn-success" />
    </div>
</div>
}

WebApplication2/Views/Consultas/Index.cshtml
@using DAO
@model List<tb_consulta>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Consultas</h2>
@*<a onclick="modalCrearCategoria()" class="btn btn-info glyphicon glyphicon-plus" title="Nuevo Cliente"></a>*@
@Html.ActionLink("Crear", "New", "Consultas")
<table class="table">
    <thead>
        <tr>
            <td>Identificador</td>
            <td>Fecha Consulta</td>
            <td>Sintomas</td>
            <td>Diagnostico</td>
            <td>Id Mascosta</td>
            <td>Nombre Mascosta</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.id_cons</td>
            <td>@item.fec_cons</td>
            <td>@item.sint_cons</td>
            <td>@item.diag_cons</td>
            <td>@item.id_mas</td>
            <td>@item.tb_mascota.nom_mas</td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id_cons }) |
                @Html.ActionLink(" ", "Delete", new { id = item.id_cons }, new
                {
                    @class = "btn btn-danger glyphicon glyphicon-remove",
                    @title = "Eliminar",
                    @onclick = "return confirm('¿Desea eliminar la Categoría?');"
                })
            </td>
        </tr>
        }
    </tbody>
</table>

WebApplication2/Views/Consultas/New.cshtml
@using DAO;
@model tb_consulta
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar Consulta</h2>
@using (Html.BeginForm())
{
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.id_cons, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.id_cons, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.fec_cons, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.fec_cons, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.sint_cons, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.sint_cons, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.diag_cons, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.diag_cons, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.id_mas, new { @class = "control-label" })
        <select class="form-control" name="id_mas">
            @foreach (var item in ViewBag.ListaMascota)
            {
                <option value="@item.id_mas">@item.id_mas</option>
            }
        </select>
    </div>
    <div class="form-group">
        <input type="submit" value="Registrar" class="btn btn-success" />
    </div>
</div>
}